ignore:
  - "Dotnet.AspNetCore.Samples.WebApi/Program.cs"
  - "Dotnet.AspNetCore.Samples.WebApi/Data"
  - "Dotnet.AspNetCore.Samples.WebApi/Migrations"
  - "Dotnet.AspNetCore.Samples.WebApi/Models"

coverage:
  status:
    project:
      controllers:
        paths:
          - Dotnet.AspNetCore.Samples.WebApi/Controllers/PlayerController.cs
      services:
        paths:
          - Dotnet.AspNetCore.Samples.WebApi/Services/PlayerService.cs
    patch:
      default:
        informational: true