ignore:
  - "Dotnet.Samples.AspNetCore.WebApi/Program.cs"
  - "Dotnet.Samples.AspNetCore.WebApi/Data"
  - "Dotnet.Samples.AspNetCore.WebApi/Migrations"
  - "Dotnet.Samples.AspNetCore.WebApi/Models"

coverage:
  status:
    project:
      controllers:
        paths:
          - Dotnet.Samples.AspNetCore.WebApi/Controllers/PlayerController.cs
      services:
        paths:
          - Dotnet.Samples.AspNetCore.WebApi/Services/PlayerService.cs
    patch:
      default:
        informational: true